image: debian:unstable
 
before_script:
  - apt update -qq
  - ./install-deps.sh
 
stages:
  - build
 
build-distcheck:
  stage: build
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - (cd libltdl; make distclean; rm configure)
    - (cd engine; ln -s ../build/engine/config.h .)
    - dpkg-buildpackage -uc -us -d -b
    - mv ../*.deb build
 
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
