image: debian:unstable
 
before_script:
  - apt update -qq
  - ./install-deps.sh
 
stages:
  - build
 
build-distcheck:
  stage: build
  script:
    - ./autogen.sh
    - ./configure
    - make distclean
    - dpkg-buildpackage -uc -us -d -b
 
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
      - ../*.deb
