os:
  - linux
  # osx
language: c
compiler: gcc
sudo: true
addons: {apt: {packages: install gforth libffi-dev yodl } }
install:
  - git clone https://github.com/GeraldWodni/swig.git
  - cd swig && ./autogen.sh && ./configure && make && sudo make install
script:
  - ./autogen.sh
  - ./configure
  - make
