os:
  - linux
  # osx
env:
  - M32=
  - M32=-m32
language: c
compiler: gcc
sudo: true
before_install:
  - sudo apt-get update
  - sudo apt-get install gforth libffi-dev libltdl7 libsoil-dev yodl
  - if [ `uname -m`$M32 = x86_64-m32 ]; then sudo apt-get --fix-missing install gcc-multilib libltdl7:i386 ; fi
  - ./install-swig.sh
script:
  - ./autogen.sh
  - ./configure --enable-lib CC="gcc $M32"
  - make
