os:
  - linux
  # osx
language: c
compiler: gcc
sudo: true
before_install:
  - sudo apt-get install gforth libffi-dev yodl
  - git clone https://github.com/GeraldWodni/swig.git
  - cd swig && ./autogen.sh && ./configure --prefix=$HOME && make
  - cd swig && make install
  - export PATH=$PATH:$HOME/bin
script:
  - ./autogen.sh
  - ./configure
  - make
