os:
  - linux
  # osx
language: c
compiler: gcc
sudo: true
before_install:
  - sudo apt-get install gforth libffi-dev libsoil-dev yodl
  - ./install-swig.sh
script:
  - ./autogen.sh
  - ./configure
  - make
