os:
  - linux
  # osx
env:
  - TARGET=c M32=
  - TARGET=c M32=-m32
  - TARGET=x86 M32=
  - TARGET=x86 M32=-m32
matrix:
  exclude:
    - os: osx
      env: TARGET=x86 M32=
    - os: osx
      env: TARGET=x86 M32=-m32
language: c
compiler: gcc
sudo: true
before_install:
  - sudo apt-get update
  - sudo apt-get install gforth libffi-dev libltdl7 libsoil-dev yodl
  - if [ `uname -m`$M32 = x86_64-m32 ]; then sudo apt-get --fix-missing install gcc-multilib libltdl7:386 ; fi
  - ./install-swig.sh
script:
  - ./autogen.sh
  - ./configure --enable-lib CC="gcc $M32"
  - make
