os:
  - linux
  - osx
env:
  - M32=
  - M32=-m32
  - EC=misc
  - EC=r8c
  - EC=8086
  - EC=c165
matrix:
  exclude:
    - os: osx
      env: EC=misc
    - os: osx
      env: EC=r8c
    - os: osx
      env: EC=8086
    - os: osx
      env: EC=c165
language: c
compiler: gcc
sudo: true
before_install: ./install-deps.sh
script:
  - ./autogen.sh
  - if [ "${TRAVIS_OS_NAME}" = osx ]; then export CC=gcc-8; fi
  - ./configure --enable-lib CC="$CC $M32"
  - make
  - if [ -n "$EC" ]; then ./build-ec $EC; fi
