os:
  - linux
  # osx
language: c
compiler: gcc
sudo: true
before_install:
  - sudo apt-get install gforth libffi-dev yodl
  - git clone https://github.com/GeraldWodni/swig.git
  - cd swig && ./autogen.sh && ./configure && make && sudo make install
script:
  - ./autogen.sh
  - ./configure
  - make
