os:
  - linux
  - osx
env:
  - M32=
  - M32=-m32
language: c
compiler: gcc
dist: trusty
sudo: required
before_install: ./install-deps.sh
script:
  - ./autogen.sh
  - export CC=gcc
  - if [ "${TRAVIS_OS_NAME}" = osx ]; then gcc -v; gcc-9 -v; export CC=gcc-9; export PATH="/usr/local/opt/texinfo/bin:/Library/TeX/texbin:$PATH"; fi
  - ./configure --enable-lib CC="$CC $M32"
  - make
  - for i in misc r8c 8086 c165; do ./build-ec $i; done
