os:
  - linux
  - osx
env:
  - M32=
  - M32=-m32
  - EC="misc r8c 8086 c165"
language: c
compiler: gcc
sudo: true
before_install: ./install-deps.sh
script:
  - ./autogen.sh
  - export CC=gcc
  - if [ "${TRAVIS_OS_NAME}" = osx ]; then gcc -v; gcc-7 -v; export CC=gcc-7; fi
  - ./configure --enable-lib CC="$CC $M32"
  - make
  - for i in $EC; do ./build-ec $i; done
