os:
  - linux
  # osx
language: c
compiler: gcc
sudo: false
addons: {apt: {packages: install gforth libffi-dev } }
install:
  - git clone https://github.com/GeraldWodni/swig.git
  - cd swig && ./configure --prefix=$HOME && make && make install
  - export PATH=$PATH:$HOME/bin
script:
  - ./autogen.sh
  - ./configure
  - make
